---
version: "3.8"
services:
  movies:
    image: manokmr1998/manoharkmoviesNetflix:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: manokmr1998/manoharktrainNetflix:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: manokmr1998/manoharkdthNetflix:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: manokmr1998/manoharkrechargeNetflix:latest
    ports:
      - 84:80
